# Generated by Django 4.2.4 on 2023-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_completedtask_user_subtask_user_tag_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='tags',
        ),
        migrations.AlterField(
            model_name='projectfolder',
            name='project_folder_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Project Folder Name'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='subtask_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Subtask Title'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Due Time'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todo_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
