# Generated by Django 4.2.4 on 2023-08-31 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_subtask_due_date_remove_todoitem_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='subtasks',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='project_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.projectfolder'),
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
