# Generated by Django 4.2.4 on 2023-09-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_todoitem_subtasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtask',
            old_name='completed_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='completedtask',
            name='category',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('work', 'Work'), ('school', 'School'), ('social', 'Social'), ('health', 'Health'), ('finances', 'Finances'), ('hobbies', 'Hobbies'), ('miscellaneous', 'Miscellaneous')], default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='due_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Due Time'),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], null=True),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='project_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.projectfolder'),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='completed_task_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title'),
        ),
    ]
